services:
  - type: web
    name: yt-autocomplete-api
    env: python
    repo: https://github.com/your-username/yt-autocomplete-api
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
